services:
  biosim-server:
    build: .
    ports:
      - "8009:8009"
    command: ["./bin/start-biosim-server", "0.0.0.0", "8009"]

  openmct-biosim:
    build:
      context: "https://github.com/scottbell/openmct-biosim.git"
    ports:
      - "9091:80"   # map host port 9091 to container port 80